#' <%=ifelse(exists("test_results") && test_results,          "@param test_results       either a numeric vector with \\eqn{p}-values or an R6 object of class \\code{\\link[DiscreteTests]{DiscreteTestResults}} from package \\link[DiscreteTests]{DiscreteTests} for which a discrete FWER procedure is to be performed.","") %>
#' <%=ifelse(exists("pCDFlist") && pCDFlist,                  "@param pCDFlist           list of the supports of the CDFs of the \\eqn{p}-values; each list item must be a numeric vector, which is sorted in increasing order and whose last element equals 1.","") %>
#' <%=ifelse(exists("alpha") && alpha,                        "@param alpha              single real number strictly between 0 and 1 indicating the target FWER level.","") %>
#' <%=ifelse(exists("independent") && independent,            "@param independent        single boolean specifying whether the \\eqn{p}-values are statistically independent or not.","") %>
#' <%=ifelse(exists("single_step") && single_step,            "@param single_step        single boolean specifying whether to perform a single-step (`TRUE`) or step-down (`FALSE`; the default) procedure.","") %>
#' <%=ifelse(exists("critical_values") && critical_values,    "@param critical_values    single boolean specifying whether critical constants are to be computed.","") %>
#' <%=ifelse(exists("select_threshold") && select_threshold,  "@param select_threshold   single real number strictly between 0 and 1 indicating the largest raw \\eqn{p}-value to be considered, i.e. only \\eqn{p}-values below this threshold are considered and the procedures are adjusted in order to take this selection effect into account; if `select_threshold = 1` (the default), all raw \\eqn{p}-values are selected.","") %>
#' <%=ifelse(exists("pCDFlist_indices") && pCDFlist_indices,  "@param pCDFlist_indices   list of numeric vectors containing the test indices that indicate to which raw \\eqn{p}-value(s) each support in `pCDFlist` belongs; if `NULL` (the default) the lengths of `test_results` and `pCDFlist` **must** be equal.","") %>
#' <%=ifelse(exists("triple_dots") && triple_dots,            "@param ...                further arguments to be passed to or from other methods. They are ignored here.","") %>
#'
#' <%=ifelse(exists("dat") && dat,                            "@param dat                input data; must be suitable for the first parameter of the provided `preprocess_fun` function or, if `preprocess_fun` is `NULL`, for the first parameter of the `test_fun` function.","") %>
#' <%=ifelse(exists("test_fun") && test_fun,                  "@param test_fun           function **from package [`DiscreteTests`][DiscreteTests::DiscreteTests-package]**, i.e. one whose name ends with `*_test_pv` and which performs hypothesis tests and provides an object with \\eqn{p}-values and their support sets; can be specified by a single character string (which is automatically checked for being a suitable function **from that package** and may be abbreviated) or a single function object.","") %>
#' <%=ifelse(exists("test_args") && test_args,                "@param test_args          optional named list with arguments for `test_fun`; the names of the list fields must match the test function's parameter names. The first parameter of the test function (i.e. the data) MUST NOT be included!","") %>
#' <%=ifelse(exists("preprocess_fun") && preprocess_fun,      "@param preprocess_fun     optional function for pre-processing the input `data`; its result must be suitable for the first parameter of the `test_fun` function.","") %>
#' <%=ifelse(exists("preprocess_args") && preprocess_args,    "@param preprocess_args    optional named list with arguments for `preprocess_fun`; the names of the list fields must match the pre-processing function's parameter names. The first parameter of the test function (i.e. the data) MUST NOT be included!","") %>
#' 
